transform:
    resize_dim: 256
    crop_dim: 224
train:
    shuffle_data: True
    batch_size: 128
    val_split_method: 'fixed-split'
    k: 3
    val_percentage: 20
    loss: 'mse'
    batch_interval: 512
    epoch_interval: 1
    num_epochs: 1000
model:
    name: 'unet'
    optimizer: 'SGD'
    lr: 0.00001
    weight_decay: 0.000001
    amsgrad: False
    momentum: 0.9
test_model: False