transform:
    resize_dim: 256
    crop_dim: 224
train:
    shuffle_data: True
    batch_size: 128
    val_split_method: 'fixed-split'
    k: 3
    val_percentage: 20
    loss: 'mse'
    batch_interval: 512
    epoch_interval: 100
    num_epochs: 10000
model:
    name: 'unet'
    optimizer: 'Adam'
    lr: 0.00008
    weight_decay: 0.0000001
    amsgrad: True
    momentum: 0.85
test_model: False