transform:
    resize_dim: 256
    crop_dim: 224
train:
    shuffle_data: True
    batch_size: 32
    val_split_method: 'fixed-split'
    k: 3
    val_percentage: 20
    loss: 'l1'
    epoch_interval: 20
    num_epochs: 1500
model:
    name: 'conv_net'
    optimizer: 'Adam'
    lr: 0.0001
    weight_decay: 0.0000001
    amsgrad: True
    momentum: 0.8
    build_on_pretrained: False
    pretrained_filename: '/models/checkpoints/last_model.pt'
dataset:
    name: 'imagenette'
    size: 'full'

