transform:
    resize_dim: 256
    crop_dim: 224
train:
    shuffle_data: True
    batch_size: 128
    val_split_method: 'fixed-split'
    k: 3
    val_percentage: 20
    loss: 'l1'
    epoch_interval: 10
    num_epochs: 100
model:
    name: 'conv_net'
    optimizer: 'Adam'
    lr: 0.00008
    weight_decay: 0.0000001
    amsgrad: True
    momentum: 0.9
test_model: False